<a href="https://colab.research.google.com/github/govindaa-sharma/MLPrcatice/blob/main/Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

In [15]:
model_name = 'facebook/bart-large-cnn'

In [21]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = TFAutoModelForSeq2SeqLM.from_pretrained(model_name)

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
All PyTorch model weights were used when initializing TFBartForConditionalGeneration.

All the weights of TFBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.


In [22]:
text = 'The rapid advancement of artificial intelligence has significantly transformed various industries, from healthcare to finance. AI-powered tools are now capable of diagnosing diseases with high accuracy, automating complex financial transactions, and even assisting in creative tasks like content generation. However, this progress also raises ethical concerns, including job displacement, data privacy issues, and the potential misuse of AI technologies. Governments and organizations worldwide are working to establish regulations to ensure responsible AI development while fostering innovation. The future of AI depends on striking a balance between technological growth and societal well-being'

In [23]:
tokenized = tokenizer(text, return_tensors='tf', max_length=1024, truncation=True)

In [24]:
tokenized

{'input_ids': <tf.Tensor: shape=(1, 110), dtype=int32, numpy=
array([[    0,   133,  6379, 19026,     9,  7350,  2316,    34,  3625,
        11229,  1337,  4510,     6,    31,  3717,     7,  2879,     4,
         4687,    12, 10711,  3270,    32,   122,  4453,     9, 25378,
        10174,  6357,    19,   239,  8611,     6, 10948,  1295,  2632,
          613,  5538,     6,     8,   190, 13390,    11,  3904,  8558,
          101,  1383,  2706,     4,   635,     6,    42,  2017,    67,
         7700, 13557,  1379,     6,   217,   633, 26260,     6,   414,
         4144,   743,     6,     8,     5,   801, 19786,     9,  4687,
         4233,     4, 26581,     8,  2665,  3612,    32,   447,     7,
         5242,  3478,     7,  1306,  2149,  4687,   709,   150, 26242,
         4695,     4,    20,   499,     9,  4687,  7971,    15,  5690,
           10,  2394,   227,  9874,   434,     8, 24032,   157,    12,
         9442,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 110), d

In [25]:
summary_tokens = model.generate(
    tokenized['input_ids'],
    min_length=30,
    max_length=100,
    length_penalty=2.0,
    num_beams=4,
    early_stopping=True
)

In [27]:
summary_text = tokenizer.decode(summary_tokens[0], skip_special_tokens=True)

In [28]:
print(f"Summary : {summary_text}")

Summary : The rapid advancement of artificial intelligence has significantly transformed various industries, from healthcare to finance. However, this progress also raises ethical concerns, including job displacement, data privacy issues, and the potential misuse of AI technologies. Governments and organizations worldwide are working to establish regulations to ensure responsible AI development.


In [34]:
import nbformat
import os

def fix_notebook(input_path, output_path):
    # Verify input file exists
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input notebook not found: {input_path}")

    nb = nbformat.read(input_path, as_version=4)

    # Fix missing 'state' key
    if 'widgets' in nb['metadata'] and 'state' not in nb['metadata']['widgets']:
        nb['metadata']['widgets']['state'] = {}

    nbformat.write(nb, output_path)

# Example usage (adjust paths):
fix_notebook("/content/drive/MyDrive/Colab Notebooks/Summarization.ipynb", "Summarization_FIXED.ipynb")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [31]:
import os
print(os.path.exists("Summarization.ipynb"))  # Should print `True`

False
